
[client_renderer]
enable_computational_server = true # if true, it needs computational_server.toml
graphics_window_enabled = true
window_mode = 0 # 0 - windowed, 1 - fullscreen
window_position = [800, 400] #in pixels [pos_x, pos_y] size_x, size_y]
window_size = [900, 500] # in pixels [pos_x, pos_y] size_x, size_y]
zoom_speed = 0.1
logical_scene = "minecraft" # main / dev_test / minecraft

# color - RGBA 0..1 float32
[client_renderer.visual_style]
color_background = [0.005, 0.005, 0.005, 1.0]
color_hud_info = [0.0, 1.0, 0.0, 1.0]
color_grid = [0.03, 0.02, 0.04, 1.0]